services:
  db-debezium:
    image: postgres-debezium
    container_name: db-debezium
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres123
    ports:
      - 6543:5432
    networks:
      - debezium
  broker:
    image: apache/kafka:latest
    container_name: kafka-debezium
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:19093,EXTERNAL://:9093,CONTROLLER://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:19093,EXTERNAL://localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    ports:
      - 19093:19093
      - 9093:9093
    networks:
      - debezium
  kconnect:
    image: debezium/connect:1.9
    ports:
      - 8083:8083
    environment:
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      BOOTSTRAP_SERVERS: broker:19093
    networks:
      - debezium
    depends_on:
      - broker
      - db  

networks:
  debezium:
    driver: bridge

